name: balena 

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build-on-balena:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: true
      matrix:
        target: [aarch64-unknown-linux-musl, armv7-unknown-linux-musleabihf, x86_64-unknown-linux-musl]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
