name: balena 

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        target:
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - arm-unknown-linux-musleabihf
          - x86_64-unknown-linux-musl
          - i586-unknown-linux-musl

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: List file 1
        shell: bash
        run: |
          ls -al target/${{ matrix.target }}/release/fatrw

      - name: Install LLVM
        run: sudo apt-get install -y llvm

      - name: LLVM Strip
        run: llvm-strip target/${{ matrix.target }}/release/fatrw

      - name: List file 2
        shell: bash
        run: |
          ls -al target/${{ matrix.target }}/release/fatrw

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: target/${{ matrix.target }}/release/fatrw
          args: --best
          strip: false

      - name: List file 3
        shell: bash
        run: |
          ls -al target/${{ matrix.target }}/release/fatrw
