name: balena 

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  build-on-balena:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch: [aarch64, amd64, armv7hf, i386, rpi]
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io/deploy-to-balena-action@master
        name: 'Build with Balena'
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: 'zahari/fatrw-${{ matrix.arch }}'
          versionbot: true
