name: Flowzone
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - 'main'
      - 'master'
jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@119f07b6c9fb7108366d6b29e087f8a3560218e2 # 4366810456-1
    secrets: inherit
    with:
      rust_binaries: true
      rust_toolchain: 1.67
      cargo_targets: |
        aarch64-unknown-linux-musl,
        armv7-unknown-linux-musleabihf,
        arm-unknown-linux-musleabihf,
        x86_64-unknown-linux-musl,
        i686-unknown-linux-musl
      protect_branch: false
