name: Flowzone
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - 'main'
      - 'master'
jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@5e4cf8c972256572790c618ae33291c2f7d5f5bb # 4496020208-1
    secrets: inherit
    with:
      rust_binaries: true
      rust_toolchain: 1.67
      cargo_targets: |
        aarch64-unknown-linux-musl,
        armv7-unknown-linux-musleabihf,
        arm-unknown-linux-musleabihf,
        x86_64-unknown-linux-musl,
        i686-unknown-linux-musl
      protect_branch: false
